### ISSUE TITLE
Add progress bar (optional estimated remaining time)

### ISSUE THREAD

**Issue by rdneagu** [asgerrud/i18n-json-translate#4]
Currently it has no feedback until it finishes translating a language so if you have a lot of phrases it will take a while to see that it actually works on the translations.

A progress bar would be nice, for current language file and overall, with percentage.

An estimated remaining time would also be nice. Every n translations (where n can be any number of translations completed), get the average time it took to complete them and show the remaining time to complete the remaining translations?

**Comment by asgerrud** [comment]
Added file progress bar in (https://github.com/asgerrud/i18n-json-translate/pull/5)
